services:
  - type: web
    name: distributed-minecraft
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_URL
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        sync: false
    healthCheckPath: /health
    numInstances: 1
    autoDeploy: true
